### ISSUE TITLE
Access-Control-Allow-Headers does not accept wildcards

### ISSUE THREAD

**Issue by prayerslayer** [zalando-stups/friboo#10] opened 2015-05-04 14:34 UTC
Relevant [StackOverflow](http://stackoverflow.com/a/13147554).

**Comment by hjacobs** [comment] 2015-05-13 14:31
this is a duplicate of https://github.com/sarnowski/swagger1st/issues/14 I believe

**Comment by hjacobs** [comment] 2015-05-22 15:25
Already fixed some time ago

**Closed as completed by hjacobs** 2015-05-22 15:25 UTC
Labels: bug
